Class 20: Group Practice Problems
These will not be handed in, but please take them seriously and do not use generative AI. These exercises are designed to familiarize you with how code works in Python and will help you learn how to generate your own in the future. Please work in a group of three. Don't hesitate to ask for help if you need it. Your instructor and TAs will be circulating. Flag us down!

Name:

Partners:

Today we will investigate the NumPy module. NumPy is short for Numerical Python, and it is based on arrays.

Start by executing the following, to import numpy as np and to import the array function.

In [ ]:
# 1
import numpy as np
from numpy import array

Create a one-dimensional array variable using the array function, in which 5 integers are stored. Also create a 1D array variable that stores 6 floats. Print both arrays and their types.

In [ ]:
# 2
int_array = array([11, 2, 33, 9, 4])
float_array = array([1.1, 2.2, 3.3, 4.8, 5.4, 6.2])
print(int_array, type(int_array))
print(float_array, type(float_array))

[11  2 33  9  4] <class 'numpy.ndarray'>
[1.1 2.2 3.3 4.8 5.4 6.2] <class 'numpy.ndarray'>

Use the dtype method to determine the type of both array variables. Note that no arguments are passed to dtype, and the parentheses are not needed.

In [ ]:
# 3
print(int_array.dtype)
print(float_array.dtype)

int64
float64

For both variables, use the ndim method to determine the number of dimensions, the shape method to determine the length of the axes, and the size method to determine the number of elements.

In [ ]:
# 4
print(int_array.ndim)
print(float_array.ndim)
print(int_array.shape)
print(float_array.shape)
print(int_array.size)
print(float_array.size)

1
1
(5,)
(6,)
5
6

OK, time for two dimensional (2D) arrays!  First, create a nested list variable that stores integers: two inner lists, each of which stores 3 integers. Then, create a 2 by 3 array variable by passing the list to the array function.  Print both variables so you can see the difference.

In [ ]:
# 5

nested_list = [[1, 2, 3], [4, 5, 6]]
two_d_array = array(nested_list)
print(nested_list)
print(two_d_array)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]

Use the ndim, shape, and size methods on your 2D array variable.

In [ ]:
# 6

print(two_d_array.ndim)
print(two_d_array.shape)
print(two_d_array.size)

2
(2, 3)
6

Create a 1D array that stores [2  5  8  11]. Do this two ways: using **arange** and **linspace**.  Make sure that the elements in the array are integers.

In [ ]:
# 7

my1d = np.arange(2, 12, 3)
print(my1d)
my1d = np.linspace(2, 11, 4, dtype = np.int16)
print(my1d)

[ 2  5  8 11]
[ 2  5  8 11]

Create a 2 by 4 array using **arange** for the numbers on the first row, and **linspace** for the numbers on the second row. Print it.

In [ ]:
# 8

my2d = array([np.arange(2, 9, 2), np.linspace(1, 8, 4, dtype = np.int16)])
print(my2d)

[[2 4 6 8]
 [1 3 5 8]]

Create and print a 3 by 5 array of all zeros (integers).

In [ ]:
# 9
zeros_array = np.zeros((3,5), dtype = np.int16)
print(zeros_array)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Create and print a 4 by 2 array of all ones (integers).

In [ ]:
# 10
ones_array = np.ones((4, 2), dtype = np.int16)
print(ones_array)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]

Create and print a 3 by 5 array of all 33's.

In [ ]:
# 11
array33 = np.full((3,5), 33)
print(array33)

[[33 33 33 33 33]
 [33 33 33 33 33]
 [33 33 33 33 33]]

Execute the following to create a random number generator, and then use that to create arrays of random floats and integers.

In [ ]:
# 12
rng = np.random.default_rng()
randfl = rng.random(4)
print(randfl)
randint = rng.integers(0, 100, 5)
print(randint)

[0.67772105 0.73338183 0.47297461 0.72885345]
[81 64 11 60 94]

Create a 2 by 4 array of random integers, in the range from 0 to 50. Hint: instead of a length of 5 as above, the third argument will be a tuple that contains the number of rows and columns.

In [ ]:
# 13
randints = rng.integers(0, 50, (2,4))
print(randints)

[[28 49  2 23]
 [15 15 25  7]]

Create a 1D array and practice indexing into it and slicing, using negative and positive indices.

In [ ]:
# 14
my1d = array([33, 2, 11, 5, 8, 4])
print(my1d[0])
print(my1d[1])
print(my1d[-1])
print(my1d[::2])
print(my1d[1::2])
print(my1d[::-1])

33
2
4
[33 11  8]
[2 5 4]
[ 4  8  5 11  2 33]

Create a 2D array and practice indexing into it and slicing.

In [ ]:
# 15
my2d = array([[1, 22, 32], [14, 5, 9]])
print(my2d)
print(my2d[0, 0])
print(my2d[0, 1])
print(my2d[0, -1])
print(my2d[1, :])
print(my2d[:, 0])
print(my2d[:, :2])

[[ 1 22 32]
 [14  5  9]]
1
22
32
[14  5  9]
[ 1 14]
[[ 1 22]
 [14  5]]

Create a 2D array and replace the first row with other numbers.

In [ ]:
# 16
my2d = array([[1, 22, 32], [14, 5, 9]])
print(my2d)
my2d[0, :] = [1, 2, 3]
print(my2d)

[[ 1 22 32]
 [14  5  9]]
[[ 1  2  3]
 [14  5  9]]

Using an array in a Boolean expression results in a logical array. Create a 1D array variable my1d and try the expression my1d < 10. (Store it in a variable and print it.)

In [ ]:
# 17
my1d = array([33, 2, 11, 5, 8, 4])
mylog = my1d < 10
print(mylog)

[False  True False  True  True  True]

Now, use your logical array to index into your original 1D array variable.

In [ ]:
# 18
print(my1d[mylog])

[2 5 8 4]

Create a 2 by 4 array. Use the reshape method to reshape it into as many other arrays as you can.

In [ ]:
# 19
my2d = array([[1, 22, 32, 1], [14, 5, 9, 2]])
print(my2d)
print(my2d.reshape(4, 2))
print(my2d.reshape(1,8))
print(my2d.reshape(8,1))

[[ 1 22 32  1]
 [14  5  9  2]]
[[ 1 22]
 [32  1]
 [14  5]
 [ 9  2]]
[[ 1 22 32  1 14  5  9  2]]
[[ 1]
 [22]
 [32]
 [ 1]
 [14]
 [ 5]
 [ 9]
 [ 2]]

Create a 2D array and transpose it. Print both.

In [ ]:
# 20
my2d = array([[1, 22, 32, 1], [14, 5, 9, 2]])
print(my2d)
print(my2d.T)

[[ 1 22 32  1]
 [14  5  9  2]]
[[ 1 14]
 [22  5]
 [32  9]
 [ 1  2]]

Create a 6 by 1 array of random integers and transpose it. Print both.

In [ ]:
# 21
my1d = rng.integers(0, 100, (6,1))
print(my1d)
print(my1d.T)

[[28]
 [20]
 [84]
 [48]
 [39]
 [48]]
[[28 20 84 48 39 48]]

Now do your thing!! Write some creative problems and post them on the Creative Problems chat for Class 20. Write some quiz problems for Friday. Quiz each other!