Class 12: Group Practice Problems
These will not be handed in, but please take them seriously and do not use generative AI. These exercises are designed to familiarize you with how code works in Python and will help you learn how to generate your own in the future. Please work in a group of three. Don't hesitate to ask for help if you need it. Your instructor and TAs will be circulating. Flag us down!

We have learned some aspects of working with the range function and for loops. Today we will learn more about range, and also the enumerate function, and tuples.

We've seen that range(n) generates a sequence of integers 0 through n-1. Specifying two arguments, e.g. range(n,m), generates a sequence of integers n through m-1.  The numbers in the sequence get generated one at a time, however. Execute the following:

In [ ]:
# 1
range(2,5)

range(2, 5)

We can use the list function to turn this into a list. Execute the following:

In [ ]:
#2
list(range(2,5))

[2, 3, 4]

The default step is 1, but by using a third argument a step value can also be specified. Execute the following:

In [ ]:
#3
list(range(2,10,2))

[2, 4, 6, 8]

The step value can be negative. For example, range(n,m,-s) generates a sequence of integers from m to n+1 in steps of -s. Execute the following:

In [ ]:
# 4
list(range(12,3,-2))

[12, 10, 8, 6, 4]

Now it's time for you to generate some sequences using list and range.  Create the sequence [1, 2, 3, 4, 5].

In [ ]:
# 5
list(range(1,6))

[1, 2, 3, 4, 5]

Create the sequence [3, 7, 11, 15, 19].

In [ ]:
# 6
list(range(3,20,4))

[3, 7, 11, 15, 19]

Create the sequence [3, 2, 1].

In [ ]:
# 7
list(range(3,0,-1))

[3, 2, 1]

What happens when the step goes beyond the specified range?  Execute the following:

In [ ]:
# 8
list(range(2, 4, 5))

[2]

Now it's time to work on some applications.  Use a for loop using range to print the integers 5 through 10 in a column. Specify a field range so that the numbers are properly right-justified.

In [ ]:
# 9
for i in range(5,11):
    print(f'{i:2d}')

 5
 6
 7
 8
 9
10

Loop to sum 3+5+7+9+11+13 and print the result. Use a running sum variable, not the sum function.

In [ ]:
# 10
mysum = 0
for i in range(3,14,2):
    mysum = mysum + i
print('Sum is',mysum)

Sum is 48

Loop to print 6 5 4 3 2 on one line.

In [ ]:
# 11
for i in range(6,1,-1):
    print(i,end=' ')
print()

6 5 4 3 2

The enumerate function returns the index and item from a sequence. Execute the following:

In [ ]:
# 12
list(enumerate([3, 2, 11]))

[(0, 3), (1, 2), (2, 11)]

This actually created a list of tuples (which we'll cover shortly!). In each, you have the index and then the item from the list. Let's use this in a for loop. Execute the following:

In [ ]:
# 13
for index, item in enumerate([3, 2, 11]):
    print(index, item)

0 3
1 2
2 11

Use enumerate and a for loop to print the indices and individual characters from a string.

In [ ]:
# 14
myword = "wonderful"
for i, c in enumerate(myword):
    print('Character', i, 'is', c)

Character 0 is w
Character 1 is o
Character 2 is n
Character 3 is d
Character 4 is e
Character 5 is r
Character 6 is f
Character 7 is u
Character 8 is l

A nested list is created for you. Use nested for loops to print each item and indices in the format "Item 0 in list 0 is 5", then "Item 1 in list 0 is 11", etc.

In [ ]:
# 15
nestlist = [[5, 11], [4, 2, 33], list(range(2,6))]

for i, onelist in enumerate(nestlist):
    for j, oneval in enumerate(onelist):
        print(f'Item {j} in list {i} is {oneval}')

Item 0 in list 0 is 5
Item 1 in list 0 is 11
Item 0 in list 1 is 4
Item 1 in list 1 is 2
Item 2 in list 1 is 33
Item 0 in list 2 is 2
Item 1 in list 2 is 3
Item 2 in list 2 is 4
Item 3 in list 2 is 5

Create a list of strings. Then, for each string, print the index of the string (naturally, e.g. 1,2,3.. instead of 0,1,2..), the number of characters in the string, and the individual characters. For example, if the first string is "Hello", the first line of output would be "Word 1 "Hello" has 5 characters: H e l l o"

In [ ]:
# 16
strlist = ["Hello", "Hi", "Ciao"]
for i, s in enumerate(strlist):
    print(f'Word {i+1} "{s}" has {len(s)} characters:', end=' ')
    for c in s:
        print(c, end=' ')
    print()

Word 1 "Hello" has 5 characters: H e l l o
Word 2 "Hi" has 2 characters: H i
Word 3 "Ciao" has 4 characters: C i a o

Let's now look at tuples. Tuples are similar to lists, but they are created using parentheses instead of square brackets, and they are immutable. Create a tuple that has 3 numbers in it.

In [ ]:
# 17
mytup = (5, 11, 22)
mytup

(5, 11, 22)

Create a tuple that has 2 words in it.

In [ ]:
# 18
("Monty", "Python")

('Monty', 'Python')

Get the length of an empty tuple.

In [ ]:
# 19
len(())

0

Print the types of (5) and (5,).

In [ ]:
# 20
print(type((5)), type((5,)))

<class 'int'> <class 'tuple'>

Create a tuple that has 8 integers in it, using the range function and tuple function. Slice into this tuple to get the first 4 items.

In [ ]:
# 21
mytup = tuple(range(1,9))
mytup[:4]

(1, 2, 3, 4)

Unpacking a tuple means putting the items from the tuple into separate variables. Execute the following:

In [ ]:
# 22
a, b, c = (1, 2, 3)
print(a, b, c)

1 2 3

Now, unpack a list.

In [ ]:
# 23
a, b, c = [1, 2, 3]
print(a, b, c)

1 2 3

Now do your thing!!  Write some creative problems and post them on the Creative Problems chat for Class 12. Write some quiz problems for Friday. Quiz each other!